'use strict';
const $=id=>document.getElementById(id);
const state={guild:null,page:'Overview',directory:null,settings:null,me:null,view:'line',average:0,editor:null,generation:0,liveEnabled:true,followNow:true,liveBusy:false,lastGraph:0};
const pages=['Overview','Messages','Voice','Status','Activities','Invites','Analytics','Member Drilldown','Channel Drilldown','Automatic Roles','Channel Counters','General Settings','Stats Settings','Permissions','History Import','Filter Presets','Dashboard Panels','API Access','Audit Log'];
const colors=['#f4c542','#6ea8ff','#5ed6bd','#b09bff','#ff9f9f','#fdab65'];
const number=value=>new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(value||0);
function el(tag,attrs={},children=[]){const node=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='text')node.textContent=v;else if(k==='class')node.className=v;else if(k.startsWith('on'))node.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='checked')node.checked=v;else if(k==='value')node.value=v;else node.setAttribute(k,v);}for(const child of children)node.append(typeof child==='string'?document.createTextNode(child):child);return node;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(state.toast);state.toast=setTimeout(()=>$('toast').hidden=true,5000);}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail||'Request failed'));return data;}
function endpoint(path){return '/api/guilds/'+state.guild+'/'+path;}
function formatDate(value){return new Date(value*1000).toLocaleString();}
function localInput(date){const d=new Date(date);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function range(days){state.followNow=true;$('from').value=localInput(days==='all'?new Date(2015,0,1):Date.now()-Number(days)*86400000);$('to').value=localInput(Date.now());}
function selected(id){return Array.from($(id).selectedOptions).map(o=>o.value);}
function selectValues(id,values){for(const option of $(id).options)option.selected=values.includes(option.value);}
function query(metric){const start=state.followNow&&$('interval').value==='half_hour'&&$('range').value==='1'?Math.floor(Date.now()/1800000)*1800-86400:new Date($('from').value).getTime()/1000,end=state.followNow?($('interval').value==='half_hour'&&$('range').value==='1'?Math.floor(Date.now()/1800000)*1800:Date.now()/1000):new Date($('to').value).getTime()/1000;if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)throw new Error('Choose a valid start and end date');return new URLSearchParams({start,end,metric,interval:$('interval').value,members:selected('members').join(','),channels:selected('channels').join(','),roles:selected('roles').join(','),activities:$('activities').value.trim(),selection_mode:$('selection_mode').value,time_unit:$('time_unit').value,compare:String($('compare').checked)});}
async function stats(metric,extra={}){const q=query(metric);for(const [k,v] of Object.entries(extra))q.set(k,v);return api(endpoint('stats')+'?'+q);}
function card(title,...children){return el('section',{class:'card'},[el('h2',{text:title}),...children]);}
function empty(text='No recorded data in this range.'){return el('div',{class:'empty',text});}
function button(text,fn,className=''){return el('button',{type:'button',text,onclick:fn,class:className});}
function error(error){toast(error.message||String(error));}
function metricCards(items){return el('div',{class:'metrics'},items.map(([label,value,meta])=>el('section',{class:'card'},[el('div',{class:'metric-line'}),el('div',{class:'metric-label',text:label}),el('div',{class:'metric-value',text:value}),el('div',{class:'metric-meta',text:meta})])));}
function svgNode(tag,attrs={},text){const node=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attrs))node.setAttribute(k,v);if(text!==undefined)node.textContent=text;return node;}
function smooth(values,n){return values.map((_,i)=>{const part=values.slice(Math.max(0,i-n+1),i+1);return part.reduce((a,b)=>a+b,0)/part.length;});}
function chart(title,series,unit='count'){
 const container=el('section',{class:'card chart-card'}),body=el('div',{class:'chart'}),legend=el('div',{class:'legend'});
 const view=el('select',{'aria-label':'Graph type'},['line','bar','area','heatmap','pie'].map(x=>el('option',{value:x,text:x[0].toUpperCase()+x.slice(1)})));view.value=state.view;
 const avg=el('input',{type:'number',min:0,max:100,value:state.average,'aria-label':'Moving average periods'});
 container.append(el('div',{class:'card-heading'},[el('h2',{text:title}),el('div',{class:'chart-tools'},[el('label',{},['Graph',view]),el('label',{},['Average',avg])])]),body,legend);
 const normalized=el('input',{type:'checkbox','aria-label':'Normalize each series'});container.querySelector('.chart-tools').append(el('label',{},['Normalize',normalized]),button('Save SVG',()=>{const svg=body.querySelector('svg');if(svg)downloadFile(new XMLSerializer().serializeToString(svg),title+'.svg','image/svg+xml');else toast('Choose a line, bar, area or pie chart first');}));normalized.onchange=draw;
 function draw(){body.replaceChildren();legend.replaceChildren();const all=series.flatMap(s=>s.data.series||[]);if(!all.length){body.append(empty());return;}
  if(view.value==='heatmap'){body.style.height='auto';body.append(heatmap(series[0].data.heatmap||{}));return;}body.style.height='';
  const width=1000,height=280,left=65,right=20,top=20,bottom=42,pw=width-left-right,ph=height-top-bottom;
  const svg=svgNode('svg',{viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':title});body.append(svg);
  const buckets=[...new Set(all.map(r=>r.bucket))].sort((a,b)=>a.includes('T')&&b.includes('T')?Date.parse(a)-Date.parse(b):a.localeCompare(b));
  if(view.value==='pie'){
   const entries=(series[0].data.channels||series[0].data.labels||[]).slice(0,10),total=entries.reduce((a,r)=>a+r.value,0);let angle=-Math.PI/2;
   if(!total){body.replaceChildren(empty());return;}
   entries.forEach((r,i)=>{const next=angle+r.value/total*Math.PI*2,cx=330,cy=140,rad=115;
    const shape=r.value===total?svgNode('circle',{cx,cy,r:rad,fill:colors[i%colors.length]}):svgNode('path',{d:`M ${cx} ${cy} L ${cx+rad*Math.cos(angle)} ${cy+rad*Math.sin(angle)} A ${rad} ${rad} 0 ${next-angle>Math.PI?1:0} 1 ${cx+rad*Math.cos(next)} ${cy+rad*Math.sin(next)} Z`,fill:colors[i%colors.length]});
    shape.append(svgNode('title',{},r.name+': '+number(r.value)));svg.append(shape);svg.append(svgNode('text',{x:520,y:25+i*24,fill:colors[i%colors.length],'font-size':14},r.name+' · '+number(r.value/total*100)+'%'));angle=next;});return;
  }
  const max=normalized.checked?100:Math.max(1,...all.map(r=>r.value));for(let i=0;i<=4;i++){const y=top+ph-i/4*ph;svg.append(svgNode('line',{x1:left,y1:y,x2:width-right,y2:y,stroke:'#2a3547'}),svgNode('text',{x:left-10,y:y+5,fill:'#99a7bd','font-size':13,'text-anchor':'end'},number(max*i/4)));}
  const x=i=>left+(buckets.length===1?pw/2:i/(buckets.length-1)*pw),y=v=>top+ph-v/max*ph;
  series.forEach((s,j)=>{const values=new Map(s.data.series.map(r=>[r.bucket,r.value])),raw=buckets.map(b=>values.get(b)||0),lineColor=colors[j%colors.length];if(normalized.checked){const peak=Math.max(1,...raw);raw.forEach((v,i)=>raw[i]=v/peak*100);}legend.append(el('span',{text:s.name,style:'--line-color:'+lineColor}));
   if(view.value==='bar'){const barWidth=Math.min(35,pw/Math.max(1,buckets.length)/series.length*.8);raw.forEach((v,i)=>{const rect=svgNode('rect',{x:x(i)+j*barWidth-series.length*barWidth/2,y:y(v),width:barWidth,height:ph-(y(v)-top),fill:lineColor,rx:2});rect.append(svgNode('title',{},buckets[i]+' · '+number(v)+' '+unit));svg.append(rect);});}
   else{if(view.value==='area')svg.append(svgNode('polygon',{points:`${x(0)},${y(0)} `+raw.map((v,i)=>`${x(i)},${y(v)}`).join(' ')+` ${x(raw.length-1)},${y(0)}`,fill:lineColor,opacity:.2}));svg.append(svgNode('polyline',{points:raw.map((v,i)=>`${x(i)},${y(v)}`).join(' '),fill:'none',stroke:lineColor,'stroke-width':2.5,'stroke-linejoin':'round'}));raw.forEach((v,i)=>{const dot=svgNode('circle',{cx:x(i),cy:y(v),r:3,fill:lineColor});dot.append(svgNode('title',{},buckets[i]+' · '+number(v)+' '+unit));svg.append(dot);});}
   const n=Math.min(100,Math.max(0,Number(avg.value)||0));if(n>1){const values=smooth(raw,n);svg.append(svgNode('polyline',{points:values.map((v,i)=>`${x(i)},${y(v)}`).join(' '),fill:'none',stroke:lineColor,'stroke-width':2,'stroke-dasharray':'6 5'}));}
  });const step=Math.max(1,Math.ceil(buckets.length/7));buckets.forEach((b,i)=>{if(i%step===0||i===buckets.length-1)svg.append(svgNode('text',{x:x(i),y:height-12,fill:'#99a7bd','font-size':13,'text-anchor':'middle'},/^\d{4}-\d{2}-\d{2}T/.test(b)?b.slice(11,16):b.slice(0,16)));});
 }
 view.addEventListener('change',()=>{state.view=view.value;draw();});avg.addEventListener('change',()=>{state.average=Number(avg.value);draw();});draw();return container;
}
function heatmap(values){const wrap=el('div',{class:'heat-wrap'}),grid=el('div',{class:'heatmap'}),maximum=Math.max(1,...Object.values(values));grid.append(el('div'));for(let h=0;h<24;h++)grid.append(el('div',{class:'heat-label',text:h}));['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].forEach((day,d)=>{grid.append(el('div',{class:'heat-label',text:day}));for(let h=0;h<24;h++){const value=values[d+':'+h]||0;grid.append(el('div',{style:`background:rgba(244,197,66,${.07+.9*value/maximum})`,title:`${day} ${h}:00 · ${number(value)}`}));}});wrap.append(grid,el('div',{class:'heat-key'},['Less',...Array.from({length:5},(_,i)=>el('span',{style:`background:rgba(244,197,66,${.1+i*.22})`})),'More']));return wrap;}
function table(title,rows,columns,onRow){
 const container=el('section',{class:'card'}),search=el('input',{class:'table-search',placeholder:'Search records','aria-label':'Search '+title}),body=el('tbody'),count=el('small');let page=0,sortKey=null,ascending=true;
 const size=el('select',{'aria-label':'Rows per page'},[25,50,100].map(n=>el('option',{value:n,text:n+' rows'}))),previous=button('Previous',()=>{page=Math.max(0,page-1);draw();}),next=button('Next',()=>{page++;draw();});
 function matches(){const result=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(search.value.toLowerCase()));if(sortKey)result.sort((a,b)=>{const x=a[sortKey],y=b[sortKey];return (typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??''),undefined,{numeric:true}))*(ascending?1:-1);});return result;}
 container.append(el('div',{class:'card-heading'},[el('h2',{text:title}),search,button('CSV',()=>{const data=matches();downloadFile([columns.map(c=>csvCell(c[0])).join(','),...data.map(r=>columns.map(c=>csvCell(r[c[1]])).join(','))].join('\r\n'),title+'.csv','text/csv');})]),el('div',{class:'table-scroll'},[el('table',{},[el('thead',{},[el('tr',{},columns.map(c=>el('th',{},[button(c[0]+' ↕',()=>{ascending=sortKey===c[1]?!ascending:true;sortKey=c[1];page=0;draw();})])))]),body])]),el('div',{class:'actions'},[count,size,previous,next]));
 function draw(){const records=matches(),limit=Number(size.value);page=Math.min(page,Math.max(0,Math.ceil(records.length/limit)-1));body.replaceChildren();records.slice(page*limit,(page+1)*limit).forEach((row,i)=>{const tr=el('tr',{class:onRow?'row-link':'',...(onRow?{tabindex:0}:{})},columns.map(([name,key,fn])=>el('td',{text:fn?fn(row[key],row,page*limit+i):row[key]??'—'})));if(onRow){tr.onclick=()=>onRow(row);tr.onkeydown=e=>{if(e.key==='Enter')onRow(row);};}body.append(tr);});if(!records.length)body.append(el('tr',{},[el('td',{colspan:columns.length,text:'No matching records.'})]));count.textContent=records.length+' records · Page '+(page+1);previous.disabled=page===0;next.disabled=(page+1)*limit>=records.length;}
 search.oninput=()=>{page=0;draw();};size.onchange=()=>{page=0;draw();};draw();return container;
}
function csvCell(value){let text=String(value??'');if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}
function downloadFile(content,filename,type){const url=URL.createObjectURL(new Blob([content],{type}));el('a',{href:url,download:filename}).click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function ranking(title,rows,kind){return table(title,rows,[['Name','name',(v,r,i)=>(i+1)+'. '+v],['Total','value',number]],row=>{if(kind==='members'){selectValues('members',[row.id]);state.page='Member Drilldown';}else{selectValues('channels',[row.id]);state.page='Channel Drilldown';}render().catch(error);});}
function navigation(){const nav=$('navigation');nav.replaceChildren();pages.forEach((page,i)=>{if(i===0||i===6||i===9)nav.append(el('div',{class:'nav-section',text:i===0?'STATISTICS':i===6?'DRILLDOWNS':'MANAGEMENT'}));const needsEdit=i>=9&&!['Filter Presets','Dashboard Panels'].includes(page);if(state.directory&&needsEdit&&state.directory.level==='view')return;nav.append(button(page,()=>{state.page=page;render().catch(error);},state.page===page?'active':''));});}
async function loadGuild(){state.generation++;$('content').hidden=true;[state.directory,state.settings]=await Promise.all([api(endpoint('directory')),api(endpoint('settings'))]);for(const kind of ['members','channels','roles']){$(kind).replaceChildren(...state.directory[kind].map(item=>el('option',{value:item.id,text:item.name})));}$('interval').value='half_hour';range(1);$('range').value='1';await loadPresets();const hash=new URLSearchParams(location.hash.slice(1));if(hash.get('guild')===state.guild){state.page=hash.get('page')||'Overview';applyQuery(Object.fromEntries(hash));}await render();}
async function loadPresets(){const presets=(await api(endpoint('objects/preset'))).filter(p=>p.enabled!==false);$('presets').replaceChildren(el('option',{value:'',text:'Choose preset'}),...presets.map(p=>el('option',{value:p.id,text:p.name})));state.presets=presets;}
function applyQuery(q){state.followNow=q.followNow==='true';if(q.start)$('from').value=localInput(Number(q.start)*1000);if(q.end)$('to').value=localInput(Number(q.end)*1000);if(q.interval)$('interval').value=q.interval;for(const k of ['members','channels','roles'])selectValues(k,(q[k]||'').split(','));$('activities').value=q.activities||'';for(const k of ['selection_mode','time_unit'])if(q[k])$(k).value=q[k];if(q.compare!==undefined)$('compare').checked=q.compare==='true';}
async function render(background=false){if(!state.guild)return;const generation=++state.generation;navigation();$('title').textContent=state.page;$('section-name').textContent=pages.indexOf(state.page)<9?'SERVER ANALYTICS':'SERVER MANAGEMENT';$('welcome').hidden=true;$('filters').hidden=pages.indexOf(state.page)>=9;$('content').hidden=false;$('export').hidden=pages.indexOf(state.page)>=9;const root=el('div');if(!background)$('content').replaceChildren(empty('Loading…'));
 if(['Overview','Messages','Voice','Status','Activities','Analytics'].includes(state.page)){
  if(state.page==='Overview'||state.page==='Analytics'){
   const [messages,voice,snapshots]=await Promise.all([stats('messages'),stats('voice'),api(endpoint('snapshots')+'?'+query('messages'))]);
   const panels=(await api(endpoint('objects/panel'))).filter(p=>p.enabled!==false);if(panels.length){for(const p of panels){const data=await panelData(p);if(!p.view||p.view==='metric')root.append(metricCards([[p.name,number(data.total),data.unit]]));else{const saved=state.view;state.view=p.view;root.append(chart(p.name,[{name:p.metric,data}],data.unit));state.view=saved;}}}const latest=snapshots.at(-1),previous=snapshots[0];root.append(metricCards([['Messages',number(messages.total),'In selected range'],['Voice '+voice.unit,number(voice.total),'In selected range'],['Active members',number(new Set([...messages.members,...voice.members].map(x=>x.id)).size),'Message or voice activity'],['Members',latest?number(latest.members):'—',latest&&previous?`${latest.members-previous.members>=0?'+':''}${latest.members-previous.members} in selected range`:'Waiting for first snapshot']]));
   root.append(el('p',{class:'graph-note',text:$('interval').value==='half_hour'&&$('range').value==='1'?'🍍 Last 24 complete hours · 48 half-hour slots · Times in '+state.settings.timezone+' · Voice counts total participant minutes.':'🍍 Graph times use '+state.settings.timezone}),chart('Message activity',[{name:'Messages',data:messages}],messages.unit),chart('Voice activity',[{name:'Voice '+voice.unit,data:voice}],voice.unit));
   if(snapshots.length)root.append(chart('Server growth',[{name:'Members',data:{series:snapshots.map(r=>({bucket:new Date(r.ts*1000).toISOString().slice(0,16),value:r.members})),heatmap:{}}}]));
   root.append(el('div',{class:'split'},[ranking('Top members · messages',messages.members,'members'),ranking('Top channels · messages',messages.channels,'channels')]));
  }else{
   const metric={Messages:'messages',Voice:'voice',Status:'status',Activities:'activity'}[state.page],data=await stats(metric);root.append(metricCards([[state.page,number(data.total),data.unit],['Active members',number(data.unique_members),'In selected range'],['Channels',number(data.channels.filter(r=>r.id).length),'With recorded activity'],['Daily average',number(data.total/Math.max(1,(data.end-data.start)/86400)),data.unit+' per day']]));
   if(data.previous)root.append(metricCards([['Previous period',number(data.previous.total),data.unit],['Change',number(data.change),data.change_percent===null?'No previous activity':number(data.change_percent)+'%'],['Average per active member',number(data.total/Math.max(1,data.unique_members)),data.unit]]));
   root.append(chart('Unique active members',[{name:'Members',data:{...data,series:data.unique_series}}],'members'));
   const graphData={...data,channels:metric==='activity'||metric==='status'?data.labels:data.channels};root.append(chart(state.page+' over time',[{name:state.page,data:graphData}],data.unit));
   if(metric==='activity'||metric==='status')root.append(table('Breakdown',data.labels,[['Name','name'],[data.unit,'value',number]]));
   root.append(el('div',{class:'split'},[ranking('Top members',data.members,'members'),ranking('Top channels',data.channels.filter(r=>r.id),'channels')]));
   if(metric==='status'){const snapshots=await api(endpoint('snapshots')+'?'+query(metric));root.append(table('Presence snapshots',snapshots,[['Time','ts',formatDate],['Online','online'],['Idle','idle'],['DnD','dnd'],['Offline','offline']]));}
  }
 }else if(state.page==='Member Drilldown'||state.page==='Channel Drilldown'){
  const kind=state.page==='Member Drilldown'?'members':'channels',ids=selected(kind);root.append(el('p',{text:`Select one or more ${kind} under More filters, then Apply filters to compare them.`}));
  if(!ids.length)root.append(empty('Choose members or channels to compare.'));else for(const metric of ['messages','voice','activity','status']){const series=await Promise.all(ids.map(async id=>({name:state.directory[kind].find(r=>r.id===id)?.name||id,data:await stats(metric,{[kind]:id,selection_mode:'include'})})));root.append(chart(({messages:'Message',voice:'Voice',activity:'Activity',status:'Status'}[metric])+' comparison',series,series[0]?.data.unit));for(const s of series)root.append(ranking(s.name+' · '+metric,s.data[kind==='members'?'channels':'members'],kind==='members'?'channels':'members'));}
 }else if(state.page==='Invites'){
  const [data,logs]=await Promise.all([stats('invites'),api(endpoint('invites')+'?'+query('invites'))]);root.append(metricCards([['Invites',number(data.total),'All recorded joins'],['Qualified',number(logs.filter(r=>r.qualification==='valid').length),'Age threshold passed'],['Pending',number(logs.filter(r=>r.qualification==='pending').length),'Waiting for join-age threshold'],['Unknown',number(logs.filter(r=>!r.code).length),'No confident attribution']]));root.append(chart('Invite activity',[{name:'Joins',data}],data.unit),el('div',{class:'split'},[ranking('Top inviters',data.members,'members'),table('Invite codes',data.channels,[['Code','name'],['Joins','value',number]])]),table('Recent invite logs',logs,[['Joined','ts',formatDate],['Member','member'],['Invite','code'],['Status','qualification'],['Reason','reason']]));
 }else if(state.page==='Automatic Roles'||state.page==='Channel Counters'){
  const kind=state.page==='Automatic Roles'?'rule':'counter',objects=await api(endpoint('objects/'+kind));root.append(el('div',{class:'card-heading'},[el('p',{text:kind==='rule'?'Assign and remove roles based on measured activity. All rules are enabled without a subscription.':'Keep channel names up to date with your community’s statistics. Live counters follow the latest value, subject to Discord rate limits.'}),button(kind==='rule'?'Create role rule':'Create counter',()=>editObject(kind), 'primary')]));if(kind==='counter')root.append(el('div',{id:'counter-live',class:'card'},[el('h2',{text:'🍍 Live counter values'}),empty('Waiting for the next live refresh…')]));const list=el('div',{class:'card'});if(!objects.length)list.append(empty(kind==='rule'?'No automatic role rules yet.':'No counters yet.'));for(const item of objects)list.append(el('div',{class:'list-item'},[el('div',{},[el('h3',{text:item.name||'Untitled'}),el('p',{text:kind==='rule'?'Role '+item.role_id+' · '+(item.cron||'every '+(item.interval_seconds||300)+' seconds'):item.template+' · '+item.metric}),el('span',{class:'badge'+(item.enabled===false?' off':''),text:item.enabled===false?'Paused':'Enabled'})]),el('div',{class:'actions'},[button('Edit',()=>editObject(kind,item)),button(item.enabled===false?'Resume':'Pause',async()=>{await api(endpoint('objects/'+kind+'/'+item.id),{method:'PUT',body:JSON.stringify({...item,enabled:item.enabled===false})});await render();}),button('Duplicate',()=>{const copy={...item,name:(item.name||'Untitled')+' copy'};delete copy.id;editObject(kind,copy);}),button('Delete',async()=>{if(confirm('Delete this configuration? Existing roles and channels will remain.')){await api(endpoint('objects/'+kind+'/'+item.id),{method:'DELETE'});await render();}},'danger')])]));root.append(list);
 }else if(['General Settings','Stats Settings','Permissions'].includes(state.page)){root.append(settingsView(state.page));
 }else if(state.page==='History Import'){
  root.append(card('Import readable message history',el('p',{text:'Choose channels in the filter bar before opening this page. Imports add missing message IDs without duplicate counts. Deleted messages and past voice, presence, activity, and invite events cannot be reconstructed.'}),el('p',{text:'Threads must be supplied explicitly by their channel IDs below. Archived threads are not automatically discovered.'})));
  const ids=el('input',{value:selected('channels').join(','),placeholder:'Channel IDs, comma separated'}),start=el('input',{type:'datetime-local',value:$('from').value}),end=el('input',{type:'datetime-local',value:$('to').value});const form=card('Start an import',el('div',{class:'editor-grid'},[el('label',{class:'wide'},['Channels or accessible thread IDs',ids]),el('label',{},['From',start]),el('label',{},['To',end])]));form.append(button('Import history',async()=>{try{const job=await api(endpoint('history'),{method:'POST',body:JSON.stringify({channels:ids.value.split(',').map(x=>x.trim()).filter(Boolean),start:new Date(start.value).getTime()/1000,end:new Date(end.value).getTime()/1000})});toast('Import started: '+job.id);await render();}catch(e){error(e);}},'primary'));root.append(form);const jobs=await api(endpoint('jobs'));root.append(table('Import jobs',jobs,[['Job','id'],['Status','status'],['Scanned','scanned'],['Added','added'],['Errors','errors',v=>v.join('; ')]]));
 }else if(state.page==='Filter Presets'||state.page==='Dashboard Panels'){
  const kind=state.page==='Filter Presets'?'preset':'panel',items=await api(endpoint('objects/'+kind));root.append(el('div',{class:'card-heading'},[el('p',{text:kind==='preset'?'Save a date range and filters for your team.':'Saved metric panels for this server. Choose metric cards or charts, with saved filters and rolling date ranges.'}),button('Create '+(kind==='preset'?'preset':'panel'),()=>kind==='preset'?savePreset():editObject('panel'),'primary')]));
  if(kind==='panel')root.append(button('Import panel',()=>importPanel()));for(const item of items){const row=card(item.name||'Untitled');row.append(el('div',{class:'actions'},[button('Edit',()=>editObject(kind,item)),button(item.enabled===false?'Resume':'Pause',async()=>{await api(endpoint('objects/'+kind+'/'+item.id),{method:'PUT',body:JSON.stringify({...item,enabled:item.enabled===false})});await render();}),button('Duplicate',()=>{const copy={...item,name:(item.name||'Untitled')+' copy'};delete copy.id;editObject(kind,copy);}),button('Delete',async()=>{if(confirm('Delete this item?')){await api(endpoint('objects/'+kind+'/'+item.id),{method:'DELETE'});await loadPresets();await render();}},'danger')]));if(kind==='panel')row.append(button('Export panel',()=>downloadJSON(item,'pineapple-panel.json')));if(kind==='preset')row.append(button('Apply preset',async()=>{applyQuery(item.query);state.page='Overview';await render();}));else{const data=await panelData(item);const saved=state.view;state.view=item.view==='metric'?saved:item.view||saved;row.append(el('div',{class:'metric-value',text:number(data.total)+' '+data.unit}),chart(item.name,[{name:item.name,data}],data.unit));state.view=saved;}root.append(row);}if(!items.length)root.append(empty('No saved items yet.'));
 }else if(state.page==='API Access'){
  root.append(card('Read-only analytics API',el('p',{text:'API keys are restricted to this server. They grant access to recorded analytics and member names. Only administrators can create or revoke keys.'}),el('pre',{text:`GET ${location.origin}${endpoint('stats')}?metric=messages\nAuthorization: Bearer YOUR_API_KEY\n\nOther read routes: /directory, /snapshots, /invites, /export`}),el('div',{class:'actions'},[button('Create API key',async()=>{try{const result=await api(endpoint('keys'),{method:'POST',body:'{}'});const output=el('pre',{text:result.key});root.prepend(card(result.note,output));}catch(e){error(e);}},'primary'),button('Revoke all API keys',async()=>{if(confirm('Revoke every API key for this server?')){await api(endpoint('keys'),{method:'DELETE'});toast('API keys revoked');}},'danger')])));
 }else if(state.page==='Audit Log'){
  const logs=await api(endpoint('audit'));root.append(table('Recent configuration and automation changes',logs,[['Time','ts',formatDate],['Actor','actor'],['Action','action'],['Details','details']]));
 }
 if(generation===state.generation){const searches=[...$('content').querySelectorAll('.table-search')].map(x=>x.value);$('content').replaceChildren(root);if(background)[...$('content').querySelectorAll('.table-search')].forEach((x,i)=>{x.value=searches[i]||'';x.dispatchEvent(new Event('input'));});syncQueryURL();}
}
const descriptions={timezone:'IANA timezone, for example America/Los_Angeles.',lookback_days:'The default number of days to show. Stored history has no subscription limit.',activity_tracking:'Track observed games, streaming, listening and other application activities.',include_bots:'Include bot accounts in message counts and tracking.',track_voice_alone:'Count voice time when no other tracked member is present.',track_muted:'Count voice time while muted.',track_deafened:'Count voice time while deafened.',notification_channel:'Optional Discord channel ID for your reference. Rule notifications use each rule’s channel.',dashboard_access:'Owners, Administrators and moderators can access the dashboard. Moderators need Timeout Members, Kick Members, Ban Members or Manage Messages. Members also allows every server member to view analytics.',viewer_roles:'Roles that may view the dashboard, even with admins-only access.',editor_roles:'Additional roles that may configure statistics, counters and ordinary automatic roles. Use this for custom MOD roles without moderation permissions.',elevate_manage_server:'Let members with Manage Server edit settings. Only Administrators can change dashboard permissions.',excluded_channels:'Hide these channel IDs from dashboard statistics and commands.',excluded_members:'Hide these member IDs from dashboard statistics and commands.',role_filter:'Default role filter. Roles are evaluated using current memberships.',aggregate_channels:'JSON mapping of target channel IDs to arrays of source channel IDs. Filters use virtual merges; source data stays available.',invite_min_account_days:'Accounts younger than this at joining are marked young.',invite_min_join_days:'Invites qualify only after this many days in the server.',invite_required_roles:'Invited members must currently have every role in this list to qualify for automatic role invite conditions.',ephemeral:'Send statistics command responses privately.',command_channels:'Restrict commands to these channel IDs; administrators can use them anywhere.'};
function settingsView(page){const fields=page==='General Settings'?['activity_tracking','include_bots','track_voice_alone','track_muted','track_deafened','ephemeral','invite_min_account_days','invite_min_join_days','invite_required_roles']:page==='Stats Settings'?['timezone','lookback_days','interval','excluded_channels','excluded_members','role_filter','filter_mode','aggregate_channels']:['dashboard_access','command_access','command_channels','viewer_roles','editor_roles','elevate_manage_server'];const form=el('form',{class:'card'}),grid=el('div',{class:'setting-grid'}),inputs={};for(const key of fields){const value=state.settings[key];let input;if(typeof value==='boolean')input=el('input',{type:'checkbox',checked:value});else if(['dashboard_access','command_access','filter_mode','interval'].includes(key)){const options=key==='interval'?['half_hour','hour','day','week','month']:key==='filter_mode'?['include','exclude']:['admins','members'];input=el('select',{},options.map(v=>el('option',{value:v,text:v})));input.value=value;}else if(key==='aggregate_channels')input=el('textarea',{value:JSON.stringify(value,null,2)});else input=el('input',{type:typeof value==='number'?'number':'text',value:Array.isArray(value)?value.join(','):value??''});inputs[key]=input;const name=key.split('_').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');grid.append(el('div',{class:'setting-row'},[el('label',{class:typeof value==='boolean'?'toggle-label':''},[name,input]),el('small',{text:descriptions[key]||'Use comma separated Discord IDs for lists.'})]));}form.append(grid,el('div',{class:'actions'},[el('button',{type:'submit',class:'primary',text:'Save settings'})]));form.addEventListener('submit',async e=>{e.preventDefault();try{const data={};for(const [key,input] of Object.entries(inputs)){const previous=state.settings[key];data[key]=typeof previous==='boolean'?input.checked:Array.isArray(previous)?input.value.split(',').map(v=>v.trim()).filter(Boolean):typeof previous==='number'?Number(input.value):key==='aggregate_channels'?JSON.parse(input.value):input.value;}await api(endpoint('settings'),{method:'PUT',body:JSON.stringify(data)});state.settings=await api(endpoint('settings'));toast('Settings saved');}catch(e){error(e);}});return form;}
function editObject(kind,item={}){
 state.editor={kind,item};$('editor-title').textContent=(item.id?'Edit ':'Create ')+{rule:'role rule',counter:'channel counter',preset:'filter preset',panel:'dashboard panel'}[kind];$('editor-error').textContent='';const root=$('editor-fields');root.replaceChildren();const fields={};const grid=el('div',{class:'editor-grid'});
 function field(key,title,value,type='text',options=null,wide=false){let input;if(options){input=el('select',{},options.map(([v,t])=>el('option',{value:v,text:t})));input.value=value??options[0]?.[0];}else input=el(type==='textarea'?'textarea':'input',{...(type==='textarea'?{}:{type}),value:value??''});fields[key]=input;grid.append(el('label',{class:wide?'wide':''},[title,input]));return input;}
 field('name','Name',item.name||'');
 if(kind==='rule'){
  field('role_id','Discord role',item.role_id,'text',state.directory.roles.map(r=>[r.id,r.name]));field('interval_seconds','Check every (seconds, minimum 60)',item.interval_seconds||300,'number');field('cron','Optional five-field cron schedule',item.cron||'');field('top_n','Optional top N members',item.top_n||'','number');field('top_metric','Top ranking metric',item.top_metric||'messages','text',['messages','voice','activity','invites'].map(v=>[v,v]));field('days','Top ranking lookback days',item.days||14,'number');field('notification_channel','Optional notification channel ID',item.notification_channel||'');
  for(const [key,title] of [['enabled','Enabled'],['permanent','Keep role permanently once earned'],['notify_dm','Notify members by DM']]){const input=el('input',{type:'checkbox',checked:key==='enabled'?item[key]!==false:!!item[key]});fields[key]=input;grid.append(el('label',{class:'toggle-label'},[title,input]));}
  field('condition','Conditions (JSON)',JSON.stringify(item.condition||{match:'all',conditions:[{metric:'messages',operator:'>=',value:100,days:14},{metric:'voice',operator:'>=',value:60,days:14}]},null,2),'textarea',null,true);
  root.append(el('p',{text:'Minutes are used for voice and activity; days for account/join age. Nest conditions with match: all or any. Every condition or group supports invert: true.'}),el('details',{},[el('summary',{text:'Advanced condition reference'}),el('pre',{text:JSON.stringify({match:'any',conditions:[{metric:'activity',activities:['Minecraft'],operator:'>=',value:120,days:30},{metric:'invites',operator:'>=',value:3,days:30},{metric:'account_age',operator:'>=',value:30},{metric:'joined_age',operator:'>=',value:7},{metric:'role',role_id:'ROLE_ID',operator:'==',value:1},{metric:'statrole',rule_id:1,operator:'==',value:1},{metric:'compare',left:'messages',right:'voice',mode:'difference',operator:'>=',value:20,days:14},{metric:'messages',operator:'<',value:1,days:14,channels:['CHANNEL_ID'],invert:false}]},null,2)})]));
 }else if(kind==='counter'){
  field('channel_id','Counter channel',item.channel_id,'text',state.directory.channels.map(r=>[r.id,r.name]));field('template','Channel name template',item.template||'🍍 Members: {value}');field('metric','Counter type',item.metric||'members','text',['members','humans','bots','online','idle','offline','roles','channels','boosts','role_members','messages','voice','activity','status','invites','clock','youtube','tiktok'].map(v=>[v,v]));field('operation','Stat operation',item.operation||'total','text',['total','unique','average','change','top'].map(v=>[v,v]));field('days','Lookback days',item.days||14,'number');field('update_mode','Update mode',item.update_mode||'live','text',[['live','Live · as Discord permits'],['scheduled','Scheduled']]);field('interval_seconds','Scheduled seconds (minimum 5)',item.interval_seconds||5,'number');field('role_id','Role ID for role-members counter',item.role_id||'');field('timezone','Clock timezone',item.timezone||state.settings.timezone);field('format','Clock format',item.format||'%H:%M');field('youtube_channel','YouTube channel ID',item.youtube_channel||'');field('youtube_stat','YouTube statistic',item.youtube_stat||'subscriberCount','text',['subscriberCount','viewCount','videoCount'].map(v=>[v,v]));field('filters','Optional member/channel/role/activity filters (JSON)',JSON.stringify({members:item.members||[],channels:item.channels||[],roles:item.roles||[],activities:item.activities||[]},null,2),'textarea',null,true);
  const enabled=el('input',{type:'checkbox',checked:item.enabled!==false});fields.enabled=enabled;grid.append(el('label',{class:'toggle-label'},['Enabled',enabled]));root.append(el('p',{text:'Create a dedicated voice or text channel in Discord first, then select it here. YouTube requires a YouTube API key. TikTok uses the account authorized by TIKTOK_ACCESS_TOKEN. Instagram counters are not implemented in this release.'}));
 }else if(kind==='preset'){field('query','Query (JSON)',JSON.stringify(item.query||Object.fromEntries(query('messages')),null,2),'textarea',null,true);}else{field('metric','Metric',item.metric||'messages','text',['messages','voice','activity','status','invites'].map(v=>[v,v]));field('view','Panel view',item.view||'metric','text',['metric','line','bar','area','heatmap','pie'].map(v=>[v,v]));field('days','Rolling lookback days',item.days||14,'number');field('query','Saved filters (JSON)',JSON.stringify(item.query||Object.fromEntries(query(item.metric||'messages')),null,2),'textarea',null,true);}
 root.append(grid);if(kind==='rule')root.prepend(conditionBuilder(fields.condition));state.editor.fields=fields;$('editor').showModal();
}
async function savePreset(){const name=prompt('Name this filter preset:');if(!name)return;try{await api(endpoint('objects/preset'),{method:'POST',body:JSON.stringify({name,query:{...Object.fromEntries(query('messages')),followNow:String(state.followNow)}})});await loadPresets();toast('Preset saved');}catch(e){error(e);}}
$('editor-form').addEventListener('submit',async e=>{e.preventDefault();const {kind,item,fields}=state.editor;try{const data={...item};for(const [key,input] of Object.entries(fields)){if(input.type==='checkbox')data[key]=input.checked;else if(['condition','query'].includes(key))data[key]=JSON.parse(input.value);else if(key==='filters')Object.assign(data,JSON.parse(input.value));else if(input.type==='number')data[key]=input.value===''?null:Number(input.value);else data[key]=input.value;}await api(endpoint('objects/'+kind+(item.id?'/'+item.id:'')),{method:item.id?'PUT':'POST',body:JSON.stringify(data)});$('editor').close();toast('Saved');await loadPresets();await render();}catch(e){$('editor-error').textContent=e.message;}});
$('close-editor').onclick=$('cancel-editor').onclick=()=>$('editor').close();
$('menu').onclick=()=>$('sidebar').classList.toggle('open');
$('guild').onchange=()=>{state.guild=$('guild').value;loadGuild().catch(error);};
$('range').onchange=()=>{range($('range').value);if($('range').value==='1')$('interval').value='half_hour';else if($('interval').value==='half_hour'&&['365','all'].includes($('range').value))$('interval').value='day';};
$('apply').onclick=$('refresh').onclick=()=>render().catch(error);
$('clear-filters').onclick=()=>{for(const id of ['members','channels','roles'])selectValues(id,[]);$('activities').value='';$('selection_mode').value='include';render().catch(error);};
$('save-preset').onclick=savePreset;
$('presets').onchange=()=>{const p=state.presets.find(x=>String(x.id)===$('presets').value);if(p){applyQuery(p.query);render().catch(error);}};
$('share-query').onclick=async()=>{try{const q=query('messages');q.set('guild',state.guild);q.set('page',state.page);q.set('followNow',String(state.followNow));await navigator.clipboard.writeText(location.origin+'/#'+q);toast('Query link copied');}catch(e){error(e);}};
$('export').onclick=()=>{try{const metric={Voice:'voice',Activities:'activity',Status:'status',Invites:'invites'}[state.page]||'messages';const q=query(metric);const group=prompt('Export: members, channels, labels, or series','members');if(group){q.set('group',group);window.location.assign(endpoint('export')+'?'+q);}}catch(e){error(e);}};
$('logout').onclick=async()=>{await api('/auth/logout',{method:'POST',body:'{}'});location.reload();};
async function init(){navigation();range(14);const health=await api('/health');$('connection').textContent=health.demo?'Read-only demo':health.bot_connected?'Bot connected':'Bot connecting';if(health.demo){$('notice').hidden=false;$('notice').textContent='DEMO · Synthetic Pineapple Planet data. Changes are disabled. This is not your live server.';$('demo-note').textContent='Local demo: log in to explore synthetic data. No Discord account is required.';}
 try{state.me=await api('/api/me');}catch(e){if(!e.message.includes('Log in'))error(e);return;}
 $('login').hidden=true;$('logout').hidden=false;$('username').textContent=state.me.user.username;$('guild').replaceChildren(...state.me.guilds.map(g=>el('option',{value:g.id,text:g.name})));if(state.me.invite_url){$('invite').hidden=false;$('invite').href=state.me.invite_url;}if(!state.me.guilds.length){$('welcome').replaceChildren(el('h2',{text:'No accessible servers yet'}),el('p',{text:'Add the bot to a server where you are an administrator, or ask an administrator to grant you dashboard access.'}));return;}const hash=new URLSearchParams(location.hash.slice(1)),wanted=hash.get('guild');state.guild=state.me.guilds.some(g=>g.id===wanted)?wanted:state.me.guilds[0].id;$('guild').value=state.guild;await loadGuild();$('live-strip').hidden=false;try{const saved=localStorage.getItem('pineapple-refresh-seconds');if(['60','120','300','600'].includes(saved))$('refresh-interval').value=saved;}catch{}await refreshLive();scheduleRefresh();}
init().catch(error);

function syncQueryURL(){if(!state.guild)return;const q=query('messages');q.set('guild',state.guild);q.set('page',state.page);q.set('followNow',String(state.followNow));history.replaceState(null,'','#'+q);}
async function refreshLive(){
 if(!state.guild||!state.liveEnabled||state.liveBusy||document.hidden)return;
 state.liveBusy=true;const guild=state.guild;
 try{const data=await api(endpoint('live'));if(guild!==state.guild)return;
  for(const [id,key] of [['live-members','members'],['live-online','online'],['live-voice','in_voice'],['live-messages','messages_24h']])$(id).textContent=number(data[key]);
  if($('counter-live')){const area=$('counter-live');area.replaceChildren(el('h2',{text:'🍍 Live counter values'}));for(const c of data.counters)area.append(el('div',{class:'list-item'},[el('div',{},[el('h3',{text:c.desired_name||'Counter '+c.id}),el('p',{text:'Discord channel: '+(c.published_name||'—')})]),el('span',{class:'badge'+(c.state==='current'?'':' warning'),text:c.state==='updating'?'Waiting for Discord':c.state})]));if(!data.counters.length)area.append(empty('No active counter workers yet.'));}$('live-updated').textContent=(data.demo?'Demo · ':data.connected?'':'Disconnected · ')+new Date(data.ts*1000).toLocaleTimeString();
  const editing=$('editor').open||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName);
  if(!editing&&pages.indexOf(state.page)<9){state.lastGraph=Date.now();await render(true);}
 }catch(e){$('live-updated').textContent=e.message;}finally{state.liveBusy=false;}
}
function scheduleRefresh(){clearInterval(state.liveTimer);state.liveTimer=setInterval(refreshLive,Number($('refresh-interval').value)*1000);}
$('refresh-interval').onchange=()=>{scheduleRefresh();try{localStorage.setItem('pineapple-refresh-seconds',$('refresh-interval').value);}catch{}refreshLive();};
$('live-toggle').onchange=()=>{state.liveEnabled=$('live-toggle').checked;$('live-updated').textContent=state.liveEnabled?'Reconnecting…':'Paused';if(state.liveEnabled)refreshLive();};
for(const id of ['from','to'])$(id).addEventListener('change',()=>{state.followNow=false;});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshLive();});

function conditionBuilder(jsonInput){
 const wrap=el('section',{class:'condition-builder'}),rows=el('div'),group=el('select',{},[['all','Match all conditions'],['any','Match any condition']].map(([v,t])=>el('option',{value:v,text:t})));
 const nodes=[];let parsed;try{parsed=JSON.parse(jsonInput.value);}catch{return wrap;}
 const existing=parsed.conditions||[parsed];
 wrap.append(el('h3',{text:'🍍 Condition builder'}),el('p',{text:'Edit simple conditions here, or use the JSON editor below for nested groups and advanced filters.'}),group,rows);
 let supported=existing.every(n=>!n.conditions&&!['compare','statrole'].includes(n.metric)&&!n.channels&&!n.activities&&!n.start&&!n.end)&&!parsed.invert;
 if(!supported){wrap.append(el('p',{text:'This rule uses advanced conditions. Its JSON is preserved below.'}));return wrap;}
 group.value=parsed.match||'all';
 function write(){jsonInput.value=JSON.stringify({match:group.value,conditions:nodes.map(n=>({...n.original,metric:n.metric.value,operator:n.op.value,value:Number(n.value.value),days:Number(n.days.value),...(n.role.value?{role_id:n.role.value}:{}),invert:n.invert.checked}))},null,2);}
 function add(original={metric:'messages',operator:'>=',value:100,days:14}){
  const metric=el('select',{},['messages','voice','activity','invites','account_age','joined_age','role'].map(v=>el('option',{value:v,text:v})));metric.value=original.metric;
  const op=el('select',{},['>=','>','<=','<','==','!='].map(v=>el('option',{value:v,text:v})));op.value=original.operator||'>=';
  const value=el('input',{type:'number',value:original.value??0,'aria-label':'Threshold'}),days=el('input',{type:'number',min:0,value:original.days??14,'aria-label':'Lookback days'}),role=el('input',{value:original.role_id||'',placeholder:'Role ID if needed','aria-label':'Role ID'}),invert=el('input',{type:'checkbox',checked:!!original.invert});
  const row=el('div',{class:'condition-row'},[el('label',{},['Metric',metric]),el('label',{},['Operator',op]),el('label',{},['Threshold',value]),el('label',{},['Days',days]),el('label',{},['Role ID',role]),el('label',{class:'toggle-label'},['Invert',invert])]);
  const node={original,metric,op,value,days,role,invert,row};nodes.push(node);row.append(button('Remove',()=>{nodes.splice(nodes.indexOf(node),1);row.remove();write();}));
  for(const input of [metric,op,value,days,role,invert])input.addEventListener('change',write);rows.append(row);
 }
 existing.forEach(add);group.addEventListener('change',write);wrap.append(button('Add condition',()=>{add();write();}));
 jsonInput.addEventListener('input',()=>{wrap.hidden=true;});return wrap;
}

function downloadJSON(value,filename){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=el('a',{href:url,download:filename});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importPanel(){const input=el('input',{type:'file',accept:'.json,application/json'});input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>262144)throw new Error('Panel file is too large');const data=JSON.parse(await file.text());if(!data.name||!['messages','voice','activity','status','invites'].includes(data.metric))throw new Error('Choose an exported Pineapple Stats panel');delete data.id;await api(endpoint('objects/panel'),{method:'POST',body:JSON.stringify(data)});toast('Panel imported');await render();}catch(e){error(e);}};input.click();}

async function panelData(panel){const filters={...(panel.query||{})};delete filters.metric;delete filters.followNow;const now=Date.now()/1000;if(panel.days){filters.start=now-panel.days*86400;filters.end=now;}return stats(panel.metric||'messages',filters);}
